#! /bin/bash

# stop script when an error occurs
set -e

psql -q -c "CREATE USER books_user SUPERUSER PASSWORD 'pass123'"
echo "Created Postgres user 'books_user'"

psql -q -c "CREATE DATABASE books WITH OWNER books_user"
echo "Created Postgres database 'books'"

cp .env
echo "Created .env containing DATABASE_URL"